version: "3"

services:

  xray:
    restart: unless-stopped
    network_mode: host
    privileged: true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    image: teddysun/xray
    container_name: xray
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/cert:/etc/xray/cert:ro
      - ./xray:/etc/xray

  v2ray:
    restart: unless-stopped
    network_mode: host
    privileged: true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./v2ray:/etc/v2ray
